name: flutter_app
description: "App Hackathon 5° Período."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_web_plugins:
    sdk: flutter
  jwt_decode: ^0.3.1
  go_router: ^15.2.3
  auto_animated: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
#  Aqui adicionamos as imagens do app
  assets:
    - assets/images/

  uses-material-design: true

